version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: meeting_summary_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword  # Bunu .env'de saklayın!
      POSTGRES_DB: meeting_summary_db
    ports:
      - "5432:5432"  # Bilgisayarınızın 5432 portunu dinler
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Veriler silinmez
volumes:
  postgres_data:  # Database kalıcı olur
